# Generated by Django 4.2.11 on 2024-04-12 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="added_as_contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contact", unique_together={("owner", "contact")},
        ),
        migrations.RemoveField(model_name="contact", name="email",),
        migrations.RemoveField(model_name="contact", name="name",),
        migrations.RemoveField(model_name="contact", name="phone",),
    ]
